format = """
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

[cmd_duration]
format = "[$duration]($style) "

[directory]
fish_style_pwd_dir_length = 1
